# the param for the llm model, to init the foundation model.
model_file = '/home/share/huadjyin/home/s_qiuping1/workspace/omics_model/bio_model/biollm/case/models/scbert/panglao_pretrain.pth'
vocab_file = '/home/share/huadjyin/home/s_qiuping1/workspace/omics_model/bio_model/biollm/case/models/scbert/gene_vocab.json'
g2v_file = '/home/share/huadjyin/home/s_qiuping1/workspace/omics_model/bio_model/biollm/case/models/scbert//gene2vec_16906.npy'
n_bins = 7
max_seq_len = 16907
use_g2v = true
embsize = 200

# task params
distributed = false
input_file = '/home/share/huadjyin/home/s_qiuping1/workspace/omics_model/bio_model/biollm/case/data/zero-shot/blood/blood.h5ad'
output_dir = '/home/share/huadjyin/home/s_qiuping1/workspace/BioLLM2/demo/cell_emb/blood/scbert'
device = 'cuda:1'
batch_size = 32

## cell embedding
model_used = "scbert"
emb_type = 'cell'
cell_emb_type='cls' # cls/ mean/ sum
var_key='feature_name' # feature_name
obs_key='cell_type'