model_file = '/home/share/huadjyin/home/s_qiuping1/workspace/omics_model/bio_model/biollm/case/models/cellplm/20230926_85M.best.ckpt'
model_param_file = '/home/share/huadjyin/home/s_qiuping1/workspace/omics_model/bio_model/biollm/case/models/cellplm/20230926_85M.config.json'
vocab_file = '/home/share/huadjyin/home/s_qiuping1/workspace/omics_model/bio_model/biollm/case/models/cellplm/vocab.json'


# task params
head_type='embedder'
distributed = false
input_file = '/home/share/huadjyin/home/s_qiuping1/workspace/omics_model/bio_model/biollm/case/data/zero-shot/gse155468.h5ad'
output_dir = '/home/share/huadjyin/home/s_qiuping1/workspace/BioLLM1/demo/cell_emb/gse155468/cellplm/'
device = 'cuda:1'
batch_size = 32


## cell embedding
model_used = "cellplm"
emb_type = 'cell'
var_key='' # feature_name
obs_key='celltype'
n_hvg=0