# the param for the llm model, to init the foundation model.
model_file = '/home/share/huadjyin/home/s_qiuping1/workspace/omics_model/bio_model/biollm/case/models/scfoundation/models.ckpt'
vocab_file = '/home/share/huadjyin/home/s_qiuping1/workspace/omics_model/bio_model/biollm/case/models/scfoundation/gene_vocab.json'
encoder_dims = 128
encoder_heads = 12
encoder_depth = 12
max_seq_len = 19264
max_none_zero_num = 5000 # for encoder if GPU is OMM

# task params
distributed = false
device = 'cuda'
batch_size = 16
do_preprocess = true
# n_hvg = 2000

## cell embedding
model_used = "scfoundation"
key = "cell"
emb_type = "cell"  # gene/gene-expression/cell
input_type = "singlecell" # "singlecell", "bulk"
tgthighres = "t4" #  the targeted high resolution (start with t) or the fold change of the high resolution (start with f), or the addtion (start with a) of the high resoultion. only valid for input_type=singlecell
pool_type = "all" # pooling type of cell embedding all/max
quantile_cutoff = 0
var_key='gene_name'


# path related
drug_smiles_file = '/home/share/huadjyin/home/s_jiangwenjian/proj/scLLM/deepcdr/torchData/223drugs_pubchem_smiles.txt'
drug_info_file = '/home/share/huadjyin/home/s_jiangwenjian/proj/scLLM/deepcdr/torchData/GDSC/1.Drug_listMon Jun 24 09_00_55 2019.csv'
cell_line_info_file = '/home/share/huadjyin/home/s_jiangwenjian/proj/scLLM/deepcdr/torchData/CCLE/Cell_lines_annotations_20181226.txt'
cancer_response_exp_file = '/home/share/huadjyin/home/s_jiangwenjian/proj/scLLM/deepcdr/torchData/CCLE/GDSC_IC50.csv'
# expression / mutation / methylation
use_gexp = true
use_mut = false
use_methy = false
gene_expression_file = '/home/share/huadjyin/home/s_jiangwenjian/proj/scLLM/deepcdr/torchData/CCLE/genomic_expression_561celllines_697genes_demap_features.csv'
genomic_mutation_file = '/home/share/huadjyin/home/s_jiangwenjian/proj/scLLM/deepcdr/torchData/CCLE/genomic_mutation_34673_demap_features.csv'
methylation_file = '/home/share/huadjyin/home/s_jiangwenjian/proj/scLLM/deepcdr/torchData/CCLE/genomic_methylation_561celllines_808genes_demap_features.csv'

# save
drug_feature_file = '/home/share/huadjyin/home/s_qiuping1/hanyuxuan/save/drug_graph_feat'
save_path = '/home/share/huadjyin/home/s_huluni/project/BioLLM2/case/drug/save'

# deepcdr params
# mode
mode = 'test' #'test' 'train'
leave_drug_test = false
leave_drug = 0
# params
israndom = false  # randomlize X and A
lr = 1e-3
# hyparameters for GCN
unit_list = [256,256,256]
use_bn = true   # use batchnormalization for GCN
use_relu = true
use_GMP =true # use GlobalMaxPooling for GCN
max_atoms = 100
