# the param for the llm model, to init the foundation model.
model_file = '/home/share/huadjyin/home/s_qiuping1/workspace/omics_model/bio_model/biollm/case/models/scgpt/best_model.pt'
model_param_file = '/home/share/huadjyin/home/s_qiuping1/workspace/omics_model/bio_model/biollm/case/models/scgpt/args.json'
vocab_file = '/home/share/huadjyin/home/s_qiuping1/workspace/omics_model/bio_model/biollm/case/models/scgpt/vocab.json'
pad_value = -2
mask_ratio = 0
append_cls = true
input_style = "binned"  # "normed_raw", "log1p", or "binned"
output_style = "binned"  # "normed_raw", "log1p", or "binned"
do_mvc = false
do_dab = false
input_emb_style = "continuous"  # "category" or "continuous" or "scaling"
cell_emb_style = "cls"  # "avg-pool" or "w-pool" or "cls"
do_sample_in_train = false  # sample the bernoulli in training
per_seq_batch_sample = false

# task params
distributed = false
device = 'cuda'
batch_size = 32
do_preprocess = true 
max_seq_len = 1200 # -1
include_zero_gene = false # true

## cell embedding
model_used = "scgpt"
emb_type = 'cell'
var_key='gene_name'


# path related
drug_smiles_file = '/home/share/huadjyin/home/s_jiangwenjian/proj/scLLM/deepcdr/torchData/223drugs_pubchem_smiles.txt'
drug_info_file = '/home/share/huadjyin/home/s_jiangwenjian/proj/scLLM/deepcdr/torchData/GDSC/1.Drug_listMon Jun 24 09_00_55 2019.csv'
cell_line_info_file = '/home/share/huadjyin/home/s_jiangwenjian/proj/scLLM/deepcdr/torchData/CCLE/Cell_lines_annotations_20181226.txt'
cancer_response_exp_file = '/home/share/huadjyin/home/s_jiangwenjian/proj/scLLM/deepcdr/torchData/CCLE/GDSC_IC50.csv'
# expression / mutation / methylation
use_gexp = true
use_mut = false
use_methy = false
gene_expression_file = '/home/share/huadjyin/home/s_jiangwenjian/proj/scLLM/deepcdr/torchData/CCLE/genomic_expression_561celllines_697genes_demap_features.csv'
genomic_mutation_file = '/home/share/huadjyin/home/s_jiangwenjian/proj/scLLM/deepcdr/torchData/CCLE/genomic_mutation_34673_demap_features.csv'
methylation_file = '/home/share/huadjyin/home/s_jiangwenjian/proj/scLLM/deepcdr/torchData/CCLE/genomic_methylation_561celllines_808genes_demap_features.csv'

# save
drug_feature_file = '/home/share/huadjyin/home/s_qiuping1/hanyuxuan/save/drug_graph_feat'
save_path = '/home/share/huadjyin/home/s_huluni/project/BioLLM2/case/drug/save'

# deepcdr params
# mode
mode = 'test' #'test' 'train'
leave_drug_test = false
leave_drug = 0
# params
israndom = false  # randomlize X and A
lr = 1e-3
# hyparameters for GCN
unit_list = [256,256,256]
use_bn = true   # use batchnormalization for GCN
use_relu = true
use_GMP =true # use GlobalMaxPooling for GCN
max_atoms = 100
