# the param for the llm model, to init the foundation model.
model_used = "scgpt"
#model_file = '/home/share/huadjyin/home/s_qiuping1/workspace/omics_model/bio_model/biollm/case/result/anno/scgpt/ms/model_18.pt'
model_file = '/home/share/huadjyin/home/s_qiuping1/workspace/omics_model/bio_model/biollm/case/models/scgpt/best_model.pt'
model_param_file = '/home/share/huadjyin/home/s_qiuping1/workspace/omics_model/bio_model/biollm/case/models/scgpt/args.json'
vocab_file = '/home/share/huadjyin/home/s_qiuping1/workspace/omics_model/bio_model/biollm/case/models/scgpt/vocab.json'
# param of task
#input_file = '/home/share/huadjyin/home/s_qiuping1/workspace/omics_model/bio_model/biollm/case/data/annotation/human/organs/ms/filtered_ms_adata.h5ad'  # h5ad for the sc express matrix
input_file = '/home/share/huadjyin/home/s_huluni/project/BioLLM2/case/mapping/data/covid/batch_covid_subsampled_train.h5ad'  # h5ad for the sc express matrix
test_file = '/home/share/huadjyin/home/s_huluni/project/BioLLM2/case/mapping/data/covid/batch_covid_subsampled_test.h5ad'  # h5ad for the sc express matrix
output_dir = '/home/share/huadjyin/home/s_qiuping1/workspace/omics_model/bio_model/biollm/case/result/anno/scgpt/covid_1200/'
label_key = 'celltype'
var_key = 'gene_name'
append_cls = true
distributed = false
finetune = true
device = 'cuda:1'
mask_ratio = 0.0
include_zero_gene = false
max_seq_len = 1201
input_style = "binned"  # "normed_raw", "log1p", or "binned"
output_style = "binned"  # "normed_raw", "log1p", or "binned"
## settings for training
nlayers_cls = 3
pad_value = -2
do_mvc = false
do_dab = false
input_emb_style = "continuous"  # "category" or "continuous" or "scaling"
cell_emb_style = "cls"  # "avg-pool" or "w-pool" or "cls"
do_sample_in_train = false  # sample the bernoulli in training
per_seq_batch_sample = false
lr = 0.0001
batch_size = 32
epochs = 20
schedule_interval = 1
schedule_ratio = 0.9
fast_transformer = true
fast_transformer_backend = "flash"
dropout = 0.2
log_interval = 100
# wandb setting
weight_bias_track = false
project_name = 'biollm_annotation'
exp_name = 'scgpt_covid'
