# the param for the llm model, to init the foundation model.
model_file = '/home/share/huadjyin/home/s_qiuping1/workspace/omics_model/bio_model/biollm/case/models/scgpt/best_model.pt'
model_param_file = '/home/share/huadjyin/home/s_qiuping1/workspace/omics_model/bio_model/biollm/case/models/scgpt/args.json'
vocab_file = '/home/share/huadjyin/home/s_qiuping1/workspace/omics_model/bio_model/biollm/case/models/scgpt/vocab.json'
pad_value = -2
mask_ratio = 0
append_cls = true
input_style = "binned"  # "normed_raw", "log1p", or "binned"
output_style = "binned"  # "normed_raw", "log1p", or "binned"
do_mvc = false
do_dab = false
input_emb_style = "continuous"  # "category" or "continuous" or "scaling"
cell_emb_style = "cls"  # "avg-pool" or "w-pool" or "cls"
do_sample_in_train = false  # sample the bernoulli in training
per_seq_batch_sample = false

# task params
distributed = false

device = 'cuda'
batch_size = 8
do_preprocess = true 
max_seq_len = 1200 # -1
include_zero_gene = false # true

## cell embedding
model_used = "scgpt"
emb_type = 'gene-expression'
obs_key = "cell_type"
var_key='feature_name'
n_hvg=0


## other
h5ad_file='/home/share/huadjyin/home/s_qiuping1/workspace/omics_model/bio_model/biollm/case/data/zero-shot/Immune_ALL_human.h5ad'
tf_genes_file='/home/share/huadjyin/home/s_huluni/chenqianqian/files_for_pyscenic/resources/hs_hgnc_tfs.txt'
database_folder='/home/share/huadjyin/home/s_huluni/chenqianqian/files_for_pyscenic/databases/'
resources_folder='/home/share/huadjyin/home/s_huluni/chenqianqian/files_for_pyscenic/resources'

output_folder='/home/share/huadjyin/home/s_huluni/project/BioLLM2/case/grn/output/GO_Molecular_Function_2023/'
gene_sets = 'GO_Cellular_Component_2025'  
#'GO_Molecular_Function_2025' 'GO_Cellular_Component_2025' 'GO_Biological_Process_2025'
